package com.trivexa.socialnetwork.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    AUTHENTICATION_ERROR,
    INVALID_TOKEN,
    EXPIRED_TOKEN,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,
    INVALID_STATE,
    MALFORMED_REQUEST,
    RATE_LIMITED,
    PAYLOAD_TOO_LARGE,
    DATABASE_ERROR,
    ACCOUNT_INACTIVE,
    INTERNAL_ERROR
}
